import {Agent} from "../../../types/agent-types";

export const dummyAgent: Agent = {
    "ID": 11050,
    "Telephone": "081703633369",
    "WAPhone": "6281703633369",
    "WAPhone2": null,
    "Name": "JANET (JBE)",
    "Address": "DARMO PERMAI UTARA 4/6, RT 004 / RW001, KEL. TANJUNGSARI, KEC. SUKOMANUNGGAL, KOTA SURABAYA",
    "Email": "janetbeatrix@gmail.com",
    "Phone": "081703633369",
    "PhoneWeChat": null,
    "PhoneCDMA": null,
    "PhoneOther": null,
    "Status": "1",
    "Code": "JBE ",
    "Name2": "JANNETE BEATRIX ",
    "Gender": "2",
    "BirthCity": "SURABAYA ",
    "BirthDate": "1991-01-03 00:00:00",
    "ContactPerson": "0817 0363 3369",
    "NPWP": "842486425614000",
    "NPWPEditCounter": 0,
    "BankName": "BCA",
    "BankBranch": "-",
    "AccName": "JANNETE BEATRIX ",
    "Position": "Business Manager",
    "BBM": null,
    "Username": "janetbeatrix@gmail.com",
    "DoverID": "7541",
    "UrbanIndoUsername": "janet",
    "EmailLamudi": null,
    "URLSegment": "janet",
    "Level": "ADVISOR_LEADER",
    "GradeLevel": null,
    "PrivateNotes": null,
    "NPWPName": "RYAN RIMANTORO TEJAKUSUMA",
    "NPWPAddress": "SIMOLANGIT 12 NO. 17 RT. 002 RW. 001 PUTAT JAYA SAWAHAN KOTA SURABAYA JAWA TIMUR",
    "NamaBuktiPotong": "JANNETE BEATRIX ",
    "Latitude": "-7.273879443037157",
    "Longitude": "112.7118502855787",
    "PIN": "030190",
    "EncryptedPIN": "28317ac22268b26728d18b45f2b1cdec",
    "IsHide": "0",
    "Up": "1",
    "GoogleID": null,
    "FacebookID": null,
    "RecruitmentType": null,
    "RecruitmentMOU": null,
    "RecruitmentPositionType": null,
    "PoinRecruitment": "0",
    "RecruitmentDescription": null,
    "ShowLocation": false,
    "LastOnline": "2025-05-22 06:44:00",
    "Caption": "",
    "ReferrerNotes": null,
    "Jabatan": null,
    "EmailTax": "janetbeatrix@gmail.com",
    "LastUpdateNPWP": "2024-10-01 09:19:21",
    "DateApproved": "2021-04-01 11:42:36",
    "StatusClosing": "Sudah Pernah",
    "DateStatusChanged": null,
    "Rumah123Total": "117",
    "RumahComTotal": "-",
    "Rumah123TotalUpdate": "2024-07-13 09:41:40",
    "RumahComTotalUpdate": "2023-08-22 10:15:04",
    "IsHideListing": false,
    "FacebookAccount": null,
    "InstagramAccount": null,
    "NonActiveCause": null,
    "ClosingCase": "64",
    "LastUpdateClosingCase": "2023-06-17 12:45:32",
    "CertificateName": "JANNETE BEATRIX ",
    "AlternateLabelOffice": null,
    "KodeUnit": "IF1",
    "ForcePassBrightOn": "0",
    "IsCRA": "0",
    "NameCRA": null,
    "IsPopUpLimitBaru": "0",
    "IsSuspended": false,
    "TokenEditPin": null,
    "ClassName": "AgentData",
    "OutDate": null,
    "MOUDate": "2018-02-14 00:00:00",
    "BankNumber": "1030372146",
    "LimitListing": 500,
    "TransparentPhoto": null,
    "Photo": {
      "ID": 1802743,
      "Title": "JANNETE BEATRIX JANET JBE TITANIUM SATELIT2",
      "Small": "https://cdn-files.brighton.co.id/Uploads/Images/1802743/y1jLgIjp/JANNETE-BEATRIX-JANET-JBE-TITANIUM-SATELIT2-Small.jpg",
      "Medium": "https://cdn-files.brighton.co.id/Uploads/Images/1802743/y1jLgIjp/JANNETE-BEATRIX-JANET-JBE-TITANIUM-SATELIT2-Medium.jpg",
      "Original": "https://cdn-files.brighton.co.id/Uploads/Images/1802743/y1jLgIjp/JANNETE-BEATRIX-JANET-JBE-TITANIUM-SATELIT2.jpg",
      "SmallWebP": null,
      "MediumWebP": null,
      "OriginalWebP": null
    },
    "LanguageAgent": null,
    "Office": {
      "ClassName": "OfficeData",
      "LastEdited": "2025-10-09 11:45:13",
      "Created": "2022-06-04 08:44:04",
      "Name": "Brighton Infinite Mayjend Sungkono",
      "Address": "Jl. Pakis Argosari, Ruko Dukuh Pakis Blok F-23 E",
      "Email": "brightoninfinite@yahoo.com",
      "Phone": "031 58282877",
      "Sort": "0",
      "Code": "BRIF",
      "City": "Mayjend Sungkono",
      "Salt": "132b511f5a5ee9bca3d9f48ee1a4106cba0093d1",
      "BirthdayDate": "2022-07-01",
      "Latitude": "-7.292637938074565",
      "Longitude": "112.72057276441795",
      "Alias": "Brighton Infinite",
      "Wilayah": "SURABAYA",
      "HierarchyCode": "225",
      "KodeUnit": "IF",
      "DirectorID": "10536",
      "LocationID": "651",
      "ProvinceID": "9",
      "ParentID": "0",
      "InventoryAreaID": "70",
      "PtID": "74",
      "PhotoID": "0",
      "OfficeHubID": "0",
      "ID": 225,
      "Logo": {
        "ID": 3766392,
        "Title": "LOGO TOK",
        "Small": "https://cdn-files.brighton.co.id/Uploads/Images/3766392/QlpdeQoI/LOGO-TOK-Small.png",
        "Medium": "https://cdn-files.brighton.co.id/Uploads/Images/3766392/QlpdeQoI/LOGO-TOK-Medium.png",
        "Original": "https://cdn-files.brighton.co.id/Uploads/Images/3766392/QlpdeQoI/LOGO-TOK.png"
      },
      "URLSegment": "https://www.brighton.co.id/hubungi/alamat-kantor/?Keyword=Brighton Infinite",
      "Location": {
        "ClassName": "LocationData",
        "LastEdited": "2024-03-27 14:54:15",
        "Created": "2016-09-04 01:29:00",
        "Title": "Surabaya",
        "RumahComCode": "IDJI29",
        "RumahComParentCode": "IDJI",
        "Rumah123City": "Surabaya",
        "Rumah123Province": "Jawa Timur",
        "Rumah123ID": "136",
        "DoverCityID": "1",
        "UrbanindoTitle": "Surabaya",
        "LamudiTitle": "Surabaya",
        "URLSegment": "surabaya",
        "Overseas": "0",
        "ProvinceID": "9",
        "PhotoID": "7773575",
        "ID": 651,
        "RecordClassName": "LocationData"
      },
      "ProgressStatus": "",
      "Link": "/hubungi/alamat-kantor/detail/brighton-infinite-mayjend-sungkono",
      "getOfficeLabel": "Brighton Infinite Mayjend Sungkono",
      "getOfficeLabelNew": "Brighton Infinite Mayjend Sungkono, Surabaya",
      "getOfficeLabelCityLocation": "Mayjend Sungkono, Surabaya",
      "LocationAndProvince": "Mayjend Sungkono - Surabaya",
      "OfficeAlias": "Brighton Infinite",
      "Path": "brighton-infinite-mayjend-sungkono"
    },
    "TotalOffices": 0,
    "BarcodeImageURL": "https://storage.googleapis.com/brighton-assets/Uploads/Files/19431749/IMhXNV3w/janetbeatrix@gmail.com_QRCode.png",
    "Link": "https://www.brighton.co.id/janet",
    "Badge": [
      {
        "ID": 2513,
        "Title": "STAR CLUB",
        "Tahun": "2024",
        "Photo": {
          "ID": 13962146,
          "Title": "11",
          "Small": "https://cdn.brighton.co.id/Uploads/Images/13962146/BIwSuEkp/11-Small.png",
          "Medium": "https://cdn.brighton.co.id/Uploads/Images/13962146/BIwSuEkp/11-Medium.png",
          "Original": "https://cdn.brighton.co.id/Uploads/Images/13962146/BIwSuEkp/11.png"
        }
      },
      {
        "ID": 1781,
        "Title": "MCKINLEY CLUB",
        "Tahun": "2022",
        "Photo": {
          "ID": 13962693,
          "Title": "19",
          "Small": "https://cdn.brighton.co.id/Uploads/Images/13962693/8vMuZBzH/19-Small.png",
          "Medium": "https://cdn.brighton.co.id/Uploads/Images/13962693/8vMuZBzH/19-Medium.png",
          "Original": "https://cdn.brighton.co.id/Uploads/Images/13962693/8vMuZBzH/19.png"
        }
      },
      {
        "ID": 1780,
        "Title": "ELITE PREMIER CLUB",
        "Tahun": "2022",
        "Photo": {
          "ID": 13962109,
          "Title": "8",
          "Small": "https://cdn.brighton.co.id/Uploads/Images/13962109/auj2zCro/8-Small.png",
          "Medium": "https://cdn.brighton.co.id/Uploads/Images/13962109/auj2zCro/8-Medium.png",
          "Original": "https://cdn.brighton.co.id/Uploads/Images/13962109/auj2zCro/8.png"
        }
      },
      {
        "ID": 1776,
        "Title": "SILVER MEMBER",
        "Tahun": "2022",
        "Photo": {
          "ID": 13961682,
          "Title": "05",
          "Small": "https://cdn.brighton.co.id/Uploads/Images/13961682/slUX1gbC/05-Small.png",
          "Medium": "https://cdn.brighton.co.id/Uploads/Images/13961682/slUX1gbC/05-Medium.png",
          "Original": "https://cdn.brighton.co.id/Uploads/Images/13961682/slUX1gbC/05.png"
        }
      },
      {
        "ID": 1778,
        "Title": "PALLADIUM MEMBER",
        "Tahun": "2022",
        "Photo": {
          "ID": 13962912,
          "Title": "Palladium",
          "Small": "https://cdn.brighton.co.id/Uploads/Images/13962912/qGZH3bd4/Palladium-Small.png",
          "Medium": "https://cdn.brighton.co.id/Uploads/Images/13962912/qGZH3bd4/Palladium-Medium.png",
          "Original": "https://cdn.brighton.co.id/Uploads/Images/13962912/qGZH3bd4/Palladium.png"
        }
      }
    ],
    "TotalListing": 359,
    "TotalSell": 315,
    "TotalRent": 44,
    "TotalPrimary": 0,
    "TotalSecondary": 359,
    "TotalNonActive": 1,
    "TotalLeaders": 0,
    "TotalCurrentSundul": 117,
    "TotalListingExpired": 41,
    "Online": false,
    "AgentRecruiterID": "0",
    "LeaderID": null,
    "LeaderName": null,
    "LeaderLevel": null,
    "Certificates": [
      {
        "Title": "Fast Track for Business Manager Angkatan 2R (BM 2)  Sesi 5",
        "TitleFull": "Sertifikasi Fast Track BM 2 2024",
        "EventStartDate": "2024-10-28 10:00:00",
        "EventEndDate": "2024-10-28 12:00:00",
        "EventStartDateReal": null,
        "EventEndDateReal": null,
        "LocationEvent": "ZOOM",
        "Topic": "Fast Track BM 2 Angkatan 2R sesi pertemuan ke 5",
        "Category": "Fast Track BM 2",
        "OfficeID": "0",
        "Sesi": "5",
        "Modul": null,
        "CertificateLink": "https://cdn.brighton.co.id/Uploads/Files/11605100/ll8eMHLA/sertifikat-JANET-(JBE)-FastTrack-BM-2.jpg"
      },
      {
        "Title": null,
        "TitleFull": "Sertifikat BM",
        "EventStartDate": null,
        "EventEndDate": null,
        "EventStartDateReal": null,
        "EventEndDateReal": null,
        "LocationEvent": null,
        "Topic": null,
        "Category": null,
        "OfficeID": null,
        "Sesi": null,
        "Modul": null,
        "CertificateLink": "https://cdn.brighton.co.id/Uploads/Files/9784854/zNXTZmrC/sertifikat-JANET-(JBE)-.jpg"
      },
      {
        "Title": "Power Of Success 2018",
        "TitleFull": "Sertifikasi Bright On 2018",
        "EventStartDate": "2018-01-01 12:00:00",
        "EventEndDate": "2018-12-31 12:00:00",
        "EventStartDateReal": "2018-09-05 00:00:00",
        "EventEndDateReal": "2018-09-07 00:00:00",
        "LocationEvent": null,
        "Topic": null,
        "Category": "Bright On",
        "OfficeID": "0",
        "Sesi": "0",
        "Modul": null,
        "CertificateLink": "https://cdn.brighton.co.id/Uploads/Files/8386488/s80uXnSY/sertifikat-JANET-(JBE)-Bright-On.jpg"
      },
      {
        "Title": "Mapping Team - Oktober 2023",
        "TitleFull": "Sertifikasi Bright Star For Business Manager 2023",
        "EventStartDate": "2023-10-05 01:30:00",
        "EventEndDate": "2023-10-12 03:30:00",
        "EventStartDateReal": null,
        "EventEndDateReal": null,
        "LocationEvent": "ZOOM",
        "Topic": "Mapping Team for Business Manager",
        "Category": "Bright Star For Business Manager",
        "OfficeID": "0",
        "Sesi": "0",
        "Modul": null,
        "CertificateLink": "https://cdn.brighton.co.id/Uploads/Files/6602606/BgAADMdk/sertifikat-JANET-(JBE)-Bright-Star-For-Business-Manager.jpg"
      },
      {
        "Title": "Public Speaking - November",
        "TitleFull": "Sertifikasi Bright Star For Business Manager 2022",
        "EventStartDate": "2022-10-12 09:00:00",
        "EventEndDate": "2022-12-20 11:00:00",
        "EventStartDateReal": "2022-10-12 09:00:00",
        "EventEndDateReal": "2022-12-20 11:00:00",
        "LocationEvent": "ZOOM",
        "Topic": null,
        "Category": "Bright Star For Business Manager",
        "OfficeID": "0",
        "Sesi": "0",
        "Modul": null,
        "CertificateLink": "https://cdn.brighton.co.id/Uploads/Files/4760552/YU0HfzpS/Design-Sertifikat-pak-iwan-7.jpg"
      },
      {
        "Title": "Strategy to Add Database Effectively - November",
        "TitleFull": "Sertifikasi Bright Star For Business Manager 2022",
        "EventStartDate": "2022-10-12 09:00:00",
        "EventEndDate": "2022-12-20 11:00:00",
        "EventStartDateReal": "2022-10-12 09:00:00",
        "EventEndDateReal": "2022-12-20 11:00:00",
        "LocationEvent": "ZOOM",
        "Topic": null,
        "Category": "Bright Star For Business Manager",
        "OfficeID": "0",
        "Sesi": "0",
        "Modul": null,
        "CertificateLink": "https://cdn.brighton.co.id/Uploads/Files/4757487/AVqS4kwS/Design-Sertifikat-pak-iwan-06.jpg"
      },
      {
        "Title": "BRIGHT STAR for AL PERIODE OKT - NOV",
        "TitleFull": "Sertifikasi Bright Star For Business Manager 2020",
        "EventStartDate": "2020-10-19 01:00:00",
        "EventEndDate": "2020-11-23 03:00:00",
        "EventStartDateReal": null,
        "EventEndDateReal": null,
        "LocationEvent": "LIVE ZOOM",
        "Topic": null,
        "Category": "Bright Star For Business Manager",
        "OfficeID": "0",
        "Sesi": "0",
        "Modul": null,
        "CertificateLink": "https://cdn-files.brighton.co.id/assets/Uploads/certificates/JANET.jpg"
      }
    ],
    "InternalLevel": null,
    "Families": [
      {
        "Name": "RYAN RIMANTORO TEJAKUSUMA ",
        "Hubungan": "Pasangan",
        "AgentID": "11050",
        "AgentFamilyID": "10536",
        "StartDate": "2025-02-13",
        "EndDate": null
      }
    ],
    "TotalPoint": 191,
    "IsReadyFitProperTest": false,
    "ShowPengajuanPrimary": true
  }